# 服务端口配置
server:
  port: 8080

spring:
  # 应用名称
  application:
    name: api_provider

  # 指定当前激活的 Spring Profile，默认为 local
  profiles:
    active: ${PROFILES_ACTIVE:local}

  # Nacos 服务发现配置
  cloud:
    nacos:
      discovery:
        # Nacos Server 地址
        server-addr: 192.168.33.33
        namespace: ${NACOS_NAMESPACE:public}
        port: 8848
        username: ${NACOS_USERNAME:admin}
        password: ${NACOS_PASSWORD:admin}

dubbo:
  # Dubbo 注册中心配置
  registry:
    # 使用 Nacos 作为注册中心
    address: nacos://${NACOS_ADDR:192.168.33.33}
    port: 8848
    # 账号
    username: ${NACOS_USERNAME:admin}
    password: ${NACOS_PASSWORD:admin}
    # 配置 Nacos 注册中心参数
    parameters:
      # 设置服务注册模式为应用级（instance）而非接口级（service）
      register-mode: instance
    use-as-config-center: false
  consumer:
    check: false
  # Dubbo 协议及端口配置
  protocol:
    name: dubbo  # 使用 Dubbo 协议
    port: 20880  # Dubbo 服务监听端口

  #  # 使用 Dubbo 3.x 推荐的元数据服务配置方式
  metadata-report:
    # 元数据服务地址（Nacos）
    address: nacos://${NACOS_ADDR:192.168.33.33}
    port: 8848
    username: admin
    password: admin

logging:
  level:
    org.apache.dubbo.registry.configured: debug
    org.apache.dubbo.common.config.Environment: debug

