# 服务端口配置
server:
  port: 9998

spring:
  # 应用名称
  application:
    name: consumer
  # 指定当前激活的 Spring Profile，默认为 local
  profiles:
    active: ${PROFILES_ACTIVE:local}
  # Nacos 服务发现配置
  cloud:
    nacos:
      discovery:
        # Nacos Server 地址
        server-addr: ${NACOS_ADDR:192.168.33.33}
        namespace: ${NACOS_NAMESPACE:public}
        port: 8848
        username: ${NACOS_USERNAME:admin}
        password: ${NACOS_PASSWORD:admin}


dubbo:
  # Dubbo 应用配置，使用 Spring 的应用名
  application:
    name: ${spring.application.name}
    qos-enable: false
  consumer:
    timeout: 3000
    retries: 2
    check: false
  # Dubbo 注册中心配置
  registry:
    # 使用 Nacos 作为注册中心
    address: nacos://${NACOS_ADDR:192.168.33.33}
    parameters:
      # 设置服务注册模式为应用级（instance）而非接口级（service）
      register-mode: instance
      register-consumer-url: true
      enable-empty-protection: true
    port: 8848
    username: ${NACOS_USERNAME:admin}
    password: ${NACOS_PASSWORD:admin}
    use-as-config-center: false
  #  # 使用 Dubbo 3.x 推荐的元数据服务配置方式
  metadata-report:
    # 元数据服务地址（Nacos）
    address: nacos://${NACOS_ADDR:192.168.33.33}
    port: 8848
    username: admin
    password: admin

logging:
  level:
    org.apache.dubbo.registry.configured: debug
    org.apache.dubbo.common.config.Environment: debug
app:
  exception:
    handler:
      type: "business"